name: 'Code Analysis'
description: 'Run code analysis for Plone backend packages'
inputs:
  base_dir:
    description: 'Base directory'
    required: false
    default: ""
  check:
    description: 'Check to be used'
    required: true
  path:
    description: 'Path to check'
    required: true
    default: "src"
runs:
  using: 'docker'
  image: 'docker://kitconcept/code-quality:latest'
  args:
    - check
    - ${{ inputs.check }}
    - ${{ inputs.path }}
  env:
    BASE_DIR: ${{ inputs.base_dir }}
